#
# algorithms - Algorithms for Practice
# Copyright Â© 2020-2021 Subhrodip Mohanta (hello@subho.xyz)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

name: Algorithms PR Checker

on:
  pull_request:
    branches: [ '**' ]
    types: [opened, synchronize, reopened]

jobs:
  
  check-pr-compilation:

    needs: check-pr-code-formatting

    strategy:
      matrix:
        platform: [ ubuntu-latest , macos-latest , windows-latest ]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@master
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build Code
        run: mvn -B clean verify 
  
  
  check-pr-code-formatting:

    strategy:
      matrix:
        platform: [ ubuntu-latest , macos-latest , windows-latest ]
    
    runs-on: ${{ matrix.platform }}

    steps:
    
    - uses: actions/checkout@master
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@master
      with:
        java-version: 1.11
    
    - uses: actions/cache@master
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
    
    - name: Verify all Java files are formatted correctly according to the Google Java Style Guide
      run: |
        mvn -e spotless:check
        echo "Run the command './mvnw spotless:apply' to fix Java formatting if this job fails"
